### ISSUE TITLE
rmt init error

### ISSUE THREAD

**Issue by DavidMStraub** [dvandyk/syncrm#3]
`rmt init . CODE` leads to:

```bash
Traceback (most recent call last):
  File "/home/straub/.local/bin/rmt", line 11, in <module>
    load_entry_point('rmt', 'console_scripts', 'rmt')()
  File "/home/straub/tmp/rmt/rmt/cli.py", line 61, in rmt_cli
    args.cmd(args)
  File "/home/straub/tmp/rmt/rmt/cli.py", line 123, in init
    api.register(args['ONE-TIME-CODE'], client_id)
TypeError: 'Namespace' object is not subscriptable
```

perhaps `args['ONE-TIME-CODE']` -> `args.ONE_TIME_CODE`? Dashes in argument names are tricky apparently.

**Comment by dvandyk** [comment]
Hah! I didn't want to register another 'client', so I didn't test this after my first attempt. Bites you in the ass...
